language: cpp

matrix:
  include:

  # -----------------
  - name: "Linux x64 clang Subzero"
  # -----------------
    dist: bionic
    addons:
      apt:
        packages:
        - clang-9
        - lld-9
 

    script:
    - export CC=clang-9 CXX=clang++-9 LD=ld.lld-9
    - cd build
    - cmake .. -DREACTOR_BACKEND=Subzero -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld-9" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld-9"
    - make -j2
    - ./gles-unittests
    - ./ReactorUnitTests

  # -----------------
  - name: "Linux x64 clang LLVM"
  # -----------------
    dist: bionic
    addons:
      apt:
        packages:
        - clang-9
        - lld-9

    script:
    - export CC=clang-9 CXX=clang++-9 LD=ld.lld-9
    - cd build
    - cmake .. -DREACTOR_BACKEND=LLVM  -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld-9" -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld-9"
    - make -j2
    - ./gles-unittests
    - ./ReactorUnitTests

  # -----------------
  - name: "Linux x64 GCC"
  # -----------------
    dist: bionic
    compiler: gcc

    script:
    - cd build
    - cmake ..
    - make -j2
    - ./gles-unittests
    - ./ReactorUnitTests

  # -----------------
  - name: "Linux arm64 GCC Cross"
  # -----------------
    dist: bionic
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-aarch64-linux-gnu
        - g++-aarch64-linux-gnu
        - libc6-dev-arm64-cross

    script:
    - cd build
    - cmake .. -DSWIFTSHADER_BUILD_SAMPLES=0 -DSWIFTSHADER_BUILD_TESTS=0 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=aarch64 -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++
    - make -j2


  # -----------------
  - name: "Linux mips64el GCC Cross"
  # -----------------
    dist: bionic
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-mips64el-linux-gnuabi64
        - g++-mips64el-linux-gnuabi64
        - libc6-dev-mips64el-cross

    script:
    - cd build
    - cmake .. -DSWIFTSHADER_BUILD_SAMPLES=0 -DSWIFTSHADER_BUILD_TESTS=0 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=mips64 -DCMAKE_C_COMPILER=mips64el-linux-gnuabi64-gcc -DCMAKE_CXX_COMPILER=mips64el-linux-gnuabi64-g++
    - make -j2

  # -----------------
  - name: "Linux ppc64le GCC Cross"
  # -----------------
    dist: bionic
    compiler: gcc

    addons:
      apt:
        packages:
        - cmake
        - gcc-powerpc64le-linux-gnu
        - g++-powerpc64le-linux-gnu
        - libc6-dev-ppc64el-cross

    script:
    - cd build
    - cmake .. -DSWIFTSHADER_BUILD_SAMPLES=0 -DSWIFTSHADER_BUILD_TESTS=0 -DCMAKE_SYSTEM_NAME=Linux -DCMAKE_SYSTEM_PROCESSOR=ppc64le -DCMAKE_C_COMPILER=powerpc64le-linux-gnu-gcc -DCMAKE_CXX_COMPILER=powerpc64le-linux-gnu-g++
    - make -j2

  # -----------------
  - name: "macOS x64 clang"
  # -----------------
    os: osx
    osx_image: xcode11.3
    compiler: clang

    addons:
      homebrew:
        packages:
          - cmake
        update: true

    script:
    - cd build
    - cmake ..
    - make -j2
    - ./gles-unittests
    - ./ReactorUnitTests
